import { ChainId, type Token } from "../types";

export const supportedTokens: Record<string, Token> = {
	//Mainnet Tokens
	[`USDC_${ChainId.Mainnet}`]: {
		chainId: ChainId.Mainnet,
		address: "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
		name: "USD Coin",
		symbol: "USDC",
		decimals: 6,
		logo: require("@/ui/assets/images/token-logos/usdc-logo.png"),
		isNative: false,
	},
	[`USDT_${ChainId.Mainnet}`]: {
		chainId: ChainId.Mainnet,
		address: "0xdAC17F958D2ee523a2206206994597C13D831ec7",
		name: "Tether USD",
		symbol: "USDT",
		decimals: 6,
		logo: require("@/ui/assets/images/token-logos/tether-logo.png"),
		isNative: false,
	},
	//Sepolia Tokens
	[`USDC_${ChainId.Sepolia}`]: {
		chainId: ChainId.Sepolia,
		address: "0x1c7d4b196cb0c7b01d743fbc6116a902379c7238",
		name: "USD Coin",
		symbol: "USDC",
		decimals: 6,
		logo: require("@/ui/assets/images/token-logos/usdc-logo.png"),
		isNative: false,
	},
	//Avalanche Tokens
	[`USDC_${ChainId.Avalanche}`]: {
		chainId: ChainId.Avalanche,
		address: "0xB97EF9Ef8734C71904D8002F8b6Bc66Dd9c48a6E",
		name: "USD Coin",
		symbol: "USDC",
		decimals: 6,
		logo: require("@/ui/assets/images/token-logos/usdc-logo.png"),
		isNative: false,
	},
	[`USDT_${ChainId.Avalanche}`]: {
		chainId: ChainId.Avalanche,
		address: "0x9702230A8Ea53601f5cD2dc00fDBc13d4dF4A8c7",
		name: "Tether USD",
		symbol: "USDT",
		decimals: 6,
		logo: require("@/ui/assets/images/token-logos/tether-logo.png"),
		isNative: false,
	},
	//Avalanche Fuji Tokens
	[`USDC_${ChainId.AvalancheFuji}`]: {
		chainId: ChainId.AvalancheFuji,
		address: "0x5425890298aed601595a70AB815c96711a31Bc65",
		name: "USD Coin",
		symbol: "USDC",
		decimals: 6,
		logo: require("@/ui/assets/images/token-logos/usdc-logo.png"),
		isNative: false,
	},
	[`USDT_${ChainId.AvalancheFuji}`]: {
		chainId: ChainId.AvalancheFuji,
		address: "0xAFDa926d549a67229D8DB529638E0BAFCDb66458",
		name: "Tether USD",
		symbol: "USDT",
		decimals: 6,
		logo: require("@/ui/assets/images/token-logos/tether-logo.png"),
		isNative: false,
	},
	[`KxSH_${ChainId.AvalancheFuji}`]: {
		chainId: ChainId.AvalancheFuji,
		address: "0xC236a4959d5671C19ED5f238e1C3a92C4a3a6b20",
		name: "Stable KES Shilling",
		symbol: "KxSH",
		decimals: 18,
		logo: require("@/ui/assets/images/token-logos/keli-logo.png"),
		isNative: false,
	},
	//Base Tokens
	[`USDC_${ChainId.Base}`]: {
		chainId: ChainId.Base,
		address: "0x833589fcd6edb6e08f4c7c32d4f71b54bda02913",
		name: "USD Coin",
		symbol: "USDC",
		decimals: 6,
		logo: require("@/ui/assets/images/token-logos/usdc-logo.png"),
		isNative: false,
	},
	[`USDT_${ChainId.Base}`]: {
		chainId: ChainId.Base,
		address: "0xfde4C96c8593536E31F229EA8f37b2ADa2699bb2",
		name: "Tether USD",
		symbol: "USDT",
		decimals: 6,
		logo: require("@/ui/assets/images/token-logos/tether-logo.png"),
		isNative: false,
	},
	//Base Sepolia Tokens
	[`USDC_${ChainId.BaseSepolia}`]: {
		chainId: ChainId.BaseSepolia,
		address: "0x036CbD53842c5426634e7929541eC2318f3dCF7e",
		name: "USD Coin",
		symbol: "USDC",
		decimals: 6,
		logo: require("@/ui/assets/images/token-logos/usdc-logo.png"),
		isNative: false,
	},
	[`USDT_${ChainId.BaseSepolia}`]: {
		chainId: ChainId.BaseSepolia,
		address: "0x22c0DB4CC9B339E34956A5699E5E95dC0E00c800",
		name: "Tether USD",
		symbol: "USDT",
		decimals: 6,
		logo: require("@/ui/assets/images/token-logos/tether-logo.png"),
		isNative: false,
	},
	[`KxSH_${ChainId.BaseSepolia}`]: {
		chainId: ChainId.BaseSepolia,
		address: "0x236d5ad19a5e5c5ae80910de96141272aef27e38",
		name: "Stable KES Shilling",
		symbol: "KxSH",
		decimals: 18,
		logo: require("@/ui/assets/images/token-logos/keli-logo.png"),
		isNative: false,
	},
	//Celo Tokens
	[`USDC_${ChainId.Celo}`]: {
		chainId: ChainId.Celo,
		address: "0xceba9300f2b948710d2653dd7b07f33a8b32118c",
		name: "USD Coin",
		symbol: "USDC",
		decimals: 6,
		logo: require("@/ui/assets/images/token-logos/usdc-logo.png"),
		isNative: false,
	},
	[`USDT_${ChainId.Celo}`]: {
		chainId: ChainId.Celo,
		address: "0x48065fbBE25f71C9282ddf5e1cD6D6A887483D5e",
		name: "Tether USD",
		symbol: "USDT",
		decimals: 6,
		logo: require("@/ui/assets/images/token-logos/tether-logo.png"),
		isNative: false,
	},
	/*Celo Alfajores Tokens
	[`USDC_${ChainId.Alfajores}`]: {
		chainId: ChainId.Alfajores,
		address: "0x2F25deB3848C207fc8E0c34035B3Ba7fC157602B",
		name: "USD Coin",
		symbol: "USDC",
		decimals: 6,
		logo: require("@/ui/assets/images/token-logos/usdc-logo.png"),
		isNative: false,
	},
	[`KELI_${ChainId.Alfajores}`]: {
		chainId: ChainId.Alfajores,
		address: "0x98e52b6ed6b0aa82175f797729486ef46a8e9fa0",
		name: "Kenyan Lira",
		symbol: "KELI",
		decimals: 6,
		logo: require("@/ui/assets/images/token-logos/keli-logo.png"),
		isNative: false,
	},*/
};
